import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { BlogList } from './components/BlogCard'
import Footer from './components/Footer'
import InstitutionCards from './components/InstitutionCards'
import NavBar from './components/NavBar'
import OurProfile from './components/OurProfile'
import Parallax from './components/Parallax'
import Projects from './components/Projects'
import StrategicAlignment from './components/StrategicAlignment'
import StrategicPlan from './components/StrategicPlan'
import FourColumnCounter from './components/FourColumnCounter'


export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Parallax/>
      <InstitutionCards/>
      <OurProfile/>
      <BlogList posts={posts}/>
      <StrategicPlan/>
      <FourColumnCounter />
      <StrategicAlignment/>
      <Projects/>
    </div>
  )
}
export async function getServerSideProps() {
  const [postsRes, imagesRes] = await Promise.all([
    axios.get('https://jsonplaceholder.typicode.com/posts'),
    axios.get('https://jsonplaceholder.typicode.com/photos')
  ]);

  const posts = postsRes.data.slice(0, 7);
  const images = imagesRes.data.slice(0, 7);

  return {
    props: {
      posts: posts.map((post, i) => ({
        ...post,
        image: images[i].url
      })),
    },
  };
}
